[account_config]
account_name = "test_account_future"

[log_config]
log_file_parent_path = "./logs"
log_level = "DEBUG"

[md_adapter_config]
adapter_name = "CTP"
product_class = ["FUTURE"]
exchange = ["SHFE","CFFEX"]
sock_type = "tcp"
# 模拟
trade_front_ip = "182.254.243.31"
trade_front_port = "30002"
market_front_ip = "182.254.243.31"
market_front_port = "30011"
# 7*24
#trade_front_ip = "182.254.243.31"
#trade_front_port = "40001"
#market_front_ip = "182.254.243.31"
#market_front_port = "40011"
broker_id = "9999"
user_id = "210468"
password = "Tangshangtao0721!"
app_id = "simnow_client_test"
auth_code = "0000000000000000"

[td_adapter_config]
adapter_name = "CTP"
product_class = ["FUTURE"]
exchange = ["SHFE","CFFEX"]
sock_type = "tcp"
# 模拟
trade_front_ip = "182.254.243.31"
trade_front_port = "30002"
# 7*24
#trade_front_ip = "182.254.243.31"
#trade_front_port = "40001"
broker_id = "9999"
user_id = "210468"
password = "Tangshangtao0721!"
app_id = "simnow_client_test"
auth_code = "0000000000000000"

[risk_control_config]
daily_order_num = 10
daily_cancel_num = 10
daily_repeat_order_num = 10

[db_config]
user = "postgres"
password = "Tt1234567890"
ip = "localhost"
port = 5432
database = "rookietrader"